version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - my_network
  back:
    build:
      context: .
    container_name: back
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - my_network
networks:
  my_network:
    driver: bridge